---
title: "310 Final Project"
author: "Nathaniel Cuadros, Ethan Leimel, and Ryan Welte"
subtitle: MGSC 310
output:
  html_document:
    df_print: paged
  html_notebook: default
---

```{r setup, include=FALSE}

# Please leave this code chunk as is. It makes some slight formatting changes to alter the output to be more aesthetically pleasing. 

library(knitr)

# Change the number in set seed to your own favorite number
set.seed(1818)
options(width=70)
options(scipen=99)


# this sets text outputted in code chunks to small
opts_chunk$set(tidy.opts=list(width.wrap=50),tidy=TRUE, size = "vsmall")  
opts_chunk$set(message = FALSE,                                          
               warning = FALSE,
               # "caching" stores objects in code chunks and only rewrites if you change things
               cache = FALSE,                               
               # automatically downloads dependency files
               autodep = TRUE,
               # 
               cache.comments = FALSE,
               # 
               collapse = TRUE,
               # change fig.width and fig.height to change the code height and width by default
               fig.width = 5.5,  
               fig.height = 4.5,
               fig.align='center')


```

```{r setup-2}

# Always print this out before your assignment
sessionInfo()
getwd()
```

<!-- ### start answering your problem set here -->
<!-- You may export your homework in either html or pdf, with the former usually being easier. 
     To export or compile your Rmd file: click above on 'Knit' then 'Knit to HTML' -->
<!-- Be sure to submit both your .Rmd file and the compiled .html or .pdf file for full credit -->


```{r setup-3}

# load all your libraries in this chunk 
library('tidyverse')
library('fs')
library('rsample')
library('ggplot2')
library('dplyr')
library('here')
library('forcats')
library('arrow')
library('sjPlot')
library('tidymodels')
library('plotROC')
library('coefplot')
library('PerformanceAnalytics')
library('rpart')       
library('rpart.plot')
library('yardstick')
library('insight')
library('caret')

# note, do not run install.packages() inside a code chunk. install them in the console outside of a code chunk. 
```

# install.packages('sjPlot')

```{r}
BTC_USDT = read_parquet(
  file <- (here::here("final_project", "BTC-USDT.parquet")),
  col_select = NULL,
  as_data_frame = TRUE,
  props = ParquetArrowReaderProperties$create()
)
ETH_USDT = read_parquet(
  file <- (here::here("final_project", "ETH-USDT.parquet")),
  col_select = NULL,
  as_data_frame = TRUE,
  props = ParquetArrowReaderProperties$create()
)
```

```{r}
print(summary(BTC_USDT))
print(summary(ETH_USDT))
```

```{r}
# BTCBuy
BTC_USDT$BTC_PriceDif <-c(BTC_USDT$close - BTC_USDT$open)
shifted = lag(BTC_USDT$BTC_PriceDif, n = 1)
BTC_USDT$BTC_LastMinPriceDiff = shifted

BTC_USDT <- BTC_USDT %>% mutate(BTCBuy = BTC_LastMinPriceDiff > 0)

#ETHBuy
ETH_USDT$ETH_PriceDif <-c(ETH_USDT$close - ETH_USDT$open)
shifted = lag(ETH_USDT$ETH_PriceDif, n = 1)
ETH_USDT$ETH_LastMinPriceDiff = shifted

ETH_USDT <- ETH_USDT %>% mutate(ETHBuy = ETH_LastMinPriceDiff > 0)

names(BTC_USDT)[1:10] <-c("BTC_Open", "BTC_High","BTC_Low","BTC_Close","BTC_Volume","BTC_QuoteAssetVolume","BTC_NumberOfTrades","BTC_TalkerBuyBaseAssetVolume","BTC_TalkerBuyQuoteAssetVolume","BTC_ETH_OpenTime")

names(ETH_USDT)[1:9] <-c("ETH_Open", "ETH_High","ETH_Low","ETH_Close","ETH_Volume","ETH_QuoteAssetVolume","ETH_NumberOfTrades","ETH_TalkerBuyBaseAssetVolume","ETH_TalkerBuyQuoteAssetVolume")

BTC_USDT1month = slice_tail(BTC_USDT, n = 43200) #one month
ETH_USDT1month = slice_tail(ETH_USDT, n = 43200) #one month

BTC_USDT1year = slice_tail(BTC_USDT, n = 525600) #one year
ETH_USDT1year = slice_tail(ETH_USDT, n = 525600) #one year

BTC_USDT11month = slice_head(BTC_USDT1year, n = 482400) #11 months
ETH_USDT11month = slice_head(ETH_USDT1year, n = 482400) #11 months


ETH_BTC_USDT11month = cbind(BTC_USDT11month, ETH_USDT11month) # training set
ETH_BTC_USDT11month = subset(ETH_BTC_USDT11month, select = -c(open_time))

ETH_BTC_USDT = cbind(BTC_USDT1month, ETH_USDT1month)  # testing set
ETH_BTC_USDT = subset(ETH_BTC_USDT, select = -c(open_time))

ETH_BTC_USDT_FULL = cbind(BTC_USDT1year, ETH_USDT1year) # full set
#ETH_BTC_USDT_FULL = subset(ETH_BTC_USDT_FULL, select -c(open_time))
```


```{r}
#print(ETH_BTC_USDT)
print(summary(ETH_BTC_USDT))
```

```{r}
colnames(ETH_BTC_USDT_FULL)
```

```{r}

logit_fit_full <- glm(BTCBuy ~ ETH_Open + ETH_High + ETH_Low + ETH_Close
                       + ETH_Volume + ETH_QuoteAssetVolume + ETH_NumberOfTrades 
                       + ETH_TalkerBuyBaseAssetVolume
                       + ETH_TalkerBuyQuoteAssetVolume,
                  family = binomial,
                  data = ETH_BTC_USDT_FULL)

options(scipen = 9)
summary(logit_fit_train)
coeffs_exp = exp(logit_fit_train$coefficients)
print(coeffs_exp)
```

```{r}
BTC_logit_fit_train <- glm(BTCBuy ~ ETH_Open + ETH_High + ETH_Low + ETH_Close
                       + ETH_Volume + ETH_QuoteAssetVolume + ETH_NumberOfTrades 
                       + ETH_TalkerBuyBaseAssetVolume
                       + ETH_TalkerBuyQuoteAssetVolume,
                  family = binomial,
                  data = ETH_BTC_USDT11month)
```

```{r}
options(scipen = 9)
summary(logit_fit_train)
```

```{r}
tidy(BTC_logit_fit_train)
```

```{r}
BTC_coeffs_exp = exp(BTC_logit_fit_train$coefficients)
print(BTC_coeffs_exp)

BTC_coef_df <- data.frame("Coefficients" = BTC_coeffs_exp)
```

```{r}
ggplot(BTC_coef_df, aes(x = BTC_coeffs_exp, y = factor(Coefficients)))+geom_bar(stat = "identity", fill = "red", color = "black") + theme_minimal()
```


```{r}
BTCBuy_train_pred <- predict(logit_fit_train, new_data = ETH_BTC_USDT11month,
                  type = "response")

BTCBuy_test_pred <- predict(logit_fit_train, newdata = ETH_BTC_USDT,
                  type = "response")
```

```{r}
BTC_results_logit_test <- data.frame(
  `truth` = ETH_BTC_USDT$BTCBuy,
  `Class1` =  BTCBuy_test_pred,
  `Class2` = 1 - BTCBuy_test_pred,
  `predicted` = as.factor(ifelse(BTCBuy_test_pred > 0.54,
                                 "TRUE","FALSE"))
)

BTC_cm_test <- conf_mat(results_logit_test, 
               truth = truth,
               estimate = predicted)

print(BTC_cm_test)
autoplot(BTC_cm_test, "heatmap")
```

```{r}
p_test <- ggplot(BTC_results_logit_test, 
            aes(m = Class1, d = truth)) + 
  geom_roc(labelsize = 3.5, 
           cutoffs.at = 
             c(0.9,0.7,0.5,0.3,0)) +
  theme_minimal(base_size = 14)

print(p_test)
calc_auc(p_test)

roc_auc(BTC_results_logit_test, 
        truth = truth, 
        estimate = predicted)
```


```{r}
BTC_results_logit_train <- data.frame(
  `truth` = ETH_BTC_USDT11month$BTCBuy,
  `Class1` =  BTCBuy_train_pred,
  `Class2` = 1 - BTCBuy_train_pred,
  `predicted` = as.factor(ifelse(BTCBuy_train_pred > 0.59, # threshold chosen from ROC curve below
                                 "TRUE","FALSE"))
)

BTC_cm_train <- conf_mat(BTC_results_logit_train, 
               truth = truth,
               estimate = predicted)

print(BTC_cm_train)
autoplot(BTC_cm_train, "heatmap")
```


```{r}
p_train <- ggplot(BTC_results_logit_train, 
            aes(m = Class1, d = truth)) + 
  geom_roc(labelsize = 3.5, 
           cutoffs.at = 
             c(0.9,0.7,0.5,0.3,0)) +
  theme_minimal(base_size = 14)

print(p_train)
calc_auc(p_train)

roc_auc(BTC_results_logit_train, 
        truth = truth, 
        estimate = predicted)
```


```{r}
# Accuracy

# MSE

get_rmse <- function(true, predictions){
  sqrt(mean((true - predictions)^2))
}

print(get_rmse(ETH_BTC_USDT11month$BTCBuy, BTCBuy_train_pred)) 
print(get_rmse(ETH_BTC_USDT$BTCBuy, BTCBuy_test_pred))

# MAE
get_mae <- function(true, predictions){
  mean(abs(true - predictions))
}

print(get_mae(ETH_BTC_USDT$BTCBuy, BTCBuy_test_pred))
print(get_mae(ETH_BTC_USDT11month$BTCBuy, BTCBuy_train_pred))
```

ETHEREUM

```{r}
ETH_logit_fit_train <- glm(ETHBuy ~ BTC_Open + BTC_High + BTC_Low 
                        + BTC_Close + BTC_Volume + BTC_QuoteAssetVolume 
                        + BTC_NumberOfTrades 
                        + BTC_TalkerBuyBaseAssetVolume 
                        + BTC_TalkerBuyQuoteAssetVolume,
                  family = binomial,
                  data = ETH_BTC_USDT11month)

options(scipen = 9)
summary(ETH_logit_fit_train)

ETH_coeffs_exp = exp(ETH_logit_fit_train$coefficients)
print(ETH_coeffs_exp)

ETH_coef_df <- data.frame("Coefficients" = ETH_coeffs_exp)
```

```{r}
ggplot(ETH_coef_df, aes(x = ETH_coeffs_exp, y = factor(Coefficients)))+geom_bar(stat = "identity", fill = "red", color = "black") + theme_minimal()
```


```{r}
ETHBuy_train_pred <- predict(ETH_logit_fit_train, newdata = ETH_BTC_USDT11month,
                  type = "response")

ETHBuy_test_pred <- predict(ETH_logit_fit_train, newdata = ETH_BTC_USDT,
                  type = "response")
```

```{r}
ETH_results_logit_test <- data.frame(
  `truth` = ETH_BTC_USDT$BTCBuy,
  `Class1` =  ETHBuy_test_pred,
  `Class2` = 1 - ETHBuy_test_pred,
  `predicted` = as.factor(ifelse(ETHBuy_test_pred > 0.56,
                                 "TRUE","FALSE"))
)

ETH_cm_test <- conf_mat(ETH_results_logit_test, 
               truth = truth,
               estimate = predicted)

print(ETH_cm_test)
autoplot(ETH_cm_test, "heatmap")
```

```{r}
ETH_p_test <- ggplot(ETH_results_logit_test, 
            aes(m = Class1, d = truth)) + 
  geom_roc(labelsize = 3.5, 
           cutoffs.at = 
             c(0.9,0.7,0.5,0.3,0)) +
  theme_minimal(base_size = 14)

print(ETH_p_test)
calc_auc(ETH_p_test)

roc_auc(ETH_results_logit_test, 
        truth = truth, 
        estimate = predicted)
```


```{r}
ETH_results_logit_train <- data.frame(
  `truth` = ETH_BTC_USDT11month$BTCBuy,
  `Class1` =  ETHBuy_train_pred,
  `Class2` = 1 - ETHBuy_train_pred,
  `predicted` = as.factor(ifelse(ETHBuy_train_pred > 0.56,
                                 "TRUE","FALSE"))
)

ETH_cm_train <- conf_mat(ETH_results_logit_train, 
               truth = truth,
               estimate = predicted)

print(ETH_cm_train)
autoplot(ETH_cm_train, "heatmap")
```

```{r}
ETH_p_train <- ggplot(ETH_results_logit_train, 
            aes(m = Class1, d = truth)) + 
  geom_roc(labelsize = 3.5, 
           cutoffs.at = 
             c(0.9,0.7,0.5,0.3,0)) +
  theme_minimal(base_size = 14)

print(ETH_p_train)
calc_auc(ETH_p_train)

roc_auc(ETH_results_logit_train, 
        truth = truth, 
        estimate = predicted)
```

```{r}
# Accuracy

# MSE

get_rmse <- function(true, predictions){
  sqrt(mean((true - predictions)^2))
}

print(get_rmse(ETH_BTC_USDT11month$BTCBuy, ETHBuy_train_pred)) 
print(get_rmse(ETH_BTC_USDT$BTCBuy, ETHBuy_test_pred))

# MAE
get_mae <- function(true, predictions){
  mean(abs(true - predictions))
}

print(get_mae(ETH_BTC_USDT$BTCBuy, ETHBuy_test_pred))
print(get_mae(ETH_BTC_USDT11month$BTCBuy, ETHBuy_train_pred))
```

