---
title: "310 Final Project FINAL"
author: "Ryan Welte"
subtitle: MGSC 310
output:
  html_document:
    df_print: paged
  html_notebook: default
---

```{r setup, include=FALSE}

# Please leave this code chunk as is. It makes some slight formatting changes to alter the output to be more aesthetically pleasing. 

library(knitr)

# Change the number in set seed to your own favorite number
set.seed(1818)
options(width=70)
options(scipen=99)


# this sets text outputted in code chunks to small
opts_chunk$set(tidy.opts=list(width.wrap=50),tidy=TRUE, size = "vsmall")  
opts_chunk$set(message = FALSE,                                          
               warning = FALSE,
               # "caching" stores objects in code chunks and only rewrites if you change things
               cache = FALSE,                               
               # automatically downloads dependency files
               autodep = TRUE,
               # 
               cache.comments = FALSE,
               # 
               collapse = TRUE,
               # change fig.width and fig.height to change the code height and width by default
               fig.width = 5.5,  
               fig.height = 4.5,
               fig.align='center')


```

```{r setup-2}

# Always print this out before your assignment
sessionInfo()
getwd()

```

<!-- ### start answering your problem set here -->
<!-- You may export your homework in either html or pdf, with the former usually being easier. 
     To export or compile your Rmd file: click above on 'Knit' then 'Knit to HTML' -->
<!-- Be sure to submit both your .Rmd file and the compiled .html or .pdf file for full credit -->


```{r setup-3}

# load all your libraries in this chunk 
library('tidyverse')
library('fs')
library('rsample')
library('ggplot2')
library('dplyr')
library('here')
library('forcats')
library('arrow')

library('glmnet')
library('glmnetUtils')
library(writexl)
library(sjlabelled)
library(sjPlot)


# note, do not run install.packages() inside a code chunk. install them in the console outside of a code chunk. 

```


```{r}
BTC_USDT = read_parquet(
  file <- (here::here("datasets", "BTC-USDT.parquet")),
  col_select = NULL,
  as_data_frame = TRUE,
  props = ParquetArrowReaderProperties$create()
)
ETH_USDT = read_parquet(
  file <- (here::here("datasets", "ETH-USDT.parquet")),
  col_select = NULL,
  as_data_frame = TRUE,
  props = ParquetArrowReaderProperties$create()
)
```

```{r}


```
```{r}
BTC_USDT$BTC_PriceDif <-c(BTC_USDT$close - BTC_USDT$open)
shifted = lag(BTC_USDT$BTC_PriceDif, n = 1)
BTC_USDT$BTC_LastMinPriceDiff = shifted

BTC_USDT <- BTC_USDT %>% mutate(BTCBuy = BTC_LastMinPriceDiff > 0)

ETH_USDT$ETH_PriceDif <-c(ETH_USDT$close - ETH_USDT$open)
shifted = lag(ETH_USDT$ETH_PriceDif, n = 1)
ETH_USDT$ETH_LastMinPriceDiff = shifted

ETH_USDT <- ETH_USDT %>% mutate(ETHBuy = ETH_LastMinPriceDiff > 0)

names(BTC_USDT)[1:10] <-c("BTC_Open", "BTC_High","BTC_Low","BTC_Close","BTC_Volume","BTC_QuoteAssetVolume","BTC_NumberOfTrades","BTC_TalkerBuyBaseAssetVolume","BTC_TalkerBuyQuoteAssetVolume","BTC_ETH_OpenTime")

names(ETH_USDT)[1:9] <-c("ETH_Open", "ETH_High","ETH_Low","ETH_Close","ETH_Volume","ETH_QuoteAssetVolume","ETH_NumberOfTrades","ETH_TalkerBuyBaseAssetVolume","ETH_TalkerBuyQuoteAssetVolume")

BTC_USDT1month = slice_tail(BTC_USDT, n = 43200) #one month
ETH_USDT1month = slice_tail(ETH_USDT, n = 43200) #one month

BTC_USDT1year = slice_tail(BTC_USDT, n = 525600) #one year
ETH_USDT1year = slice_tail(ETH_USDT, n = 525600) #one year

BTC_USDT11month = slice_head(BTC_USDT1year, n = 482400) #11 months
ETH_USDT11month = slice_head(ETH_USDT1year, n = 482400) #11 months


ETH_BTC_USDT11month = cbind(BTC_USDT11month, ETH_USDT11month)
ETH_BTC_USDT11month = subset(ETH_BTC_USDT11month, select = -c(open_time))

ETH_BTC_USDT = cbind(BTC_USDT1month, ETH_USDT1month)
ETH_BTC_USDT = subset(ETH_BTC_USDT, select = -c(open_time))


write_xlsx(ETH_BTC_USDT, "ETH_BTC_USDTtoEXC_FINAL.xlsx")

```

```{r}


```

```{r}
library("scatterplot3d")
head(ETH_BTC_USDT)
#scatterplot3d(x, y=NULL, z=NULL)
#catterplot3d(ETH_BTC_USDT[5,8,20])
#scatterplot3d(ETH_BTC_USDT["ETH_Volume", "ETH_PriceDif", "BTC_ETH_OpenTime"])
#scatterplot3d(ETH_BTC_USDT[5:8:20])
#scatterplot3d(ETH_BTC_USDT[5:6,8:9,20:21])

newDFforGraph <- select(ETH_BTC_USDT, c("ETH_Volume", "ETH_PriceDif", "BTC_ETH_OpenTime"))
newDFforGraph

newDFforGraph2 <- select(ETH_BTC_USDT, c("ETH_Close", "ETH_Volume", "BTC_Volume"))


#scatterplot3d(newDFforGraph[,1:3], xlim = c(0, 20000), ylim = c(-50, 300), zlim = c(-50, 300))
scatterplot3d(newDFforGraph[,1:3], xlim = c(100, 10000), ylim = c(-35, 60))

scatterplot3d(newDFforGraph2[,1:3], xlim = c(0, 5000), ylim = c(-50, 300), zlim = c(-50, 300))

```

```{r}
```


```{r}




```





```{r}


total_split <- initial_split(ETH_BTC_USDT, 0.9)
total_train <- training(total_split)
total_test <- testing(total_split)


lm_mod1 = lm(ETH_Close ~ ETH_Volume + BTC_Close + BTC_Volume + BTC_PriceDif, data = total_train)
lm_mod2 = lm(BTC_Close ~  BTC_Volume+ ETH_Close + ETH_Volume + ETH_PriceDif, data = total_train)

summary(lm_mod1)
summary(lm_mod2)

preds_train <- predict(lm_mod1, newdata = total_train)
preds_test <- predict(lm_mod1, newdata = total_test)

tab_model(lm_mod1)
tab_model(lm_mod2)

plot_model(lm_mod1)
plot_model(lm_mod2)




#library(sjPlot)
#library(sjmisc)


#tab_model(m.lm_mod1)

#sjt.lm(lm_mod1, lm_mod2)




#preds_train
```

```{r}
total_split <- initial_split(ETH_BTC_USDT, 0.9)
total_train <- training(total_split)
total_test <- testing(total_split)

lm_mod1 = lm(ETH_Close ~  BTC_Volume+  BTC_Close + ETH_Volume + BTC_PriceDif, data = total_train)
summary(lm_mod1)
lm_mod2 = lm(BTC_Close ~ BTC_Volume + ETH_Close + ETH_Volume + ETH_PriceDif, data = total_train)
summary(lm_mod2)

preds_train <- predict(lm_mod1, newdata = total_train)
preds_test <- predict(lm_mod1, newdata = total_test)

plot_model(lm_mod1)
plot_model(lm_mod2)


```

```{r}


coef(lm_mod1)

ggplot(lm_mod1$model, aes_string(x = names(lm_mod1$model)[2], y = names(lm_mod1$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "blue") +
  labs(title = paste("Adj R2 = ",signif(summary(lm_mod1)$adj.r.squared, 5),
                     "Intercept =",signif(lm_mod1$coef[[1]],5 ),
                     "Slope =",signif(lm_mod1$coef[[2]], 5),
                     "P-Val =",signif(summary(lm_mod1)$coef[2,4], 5))) + xlim(20,15000) + ylim(1500, 3000)


#https://sejohnston.com/2012/08/09/a-quick-and-easy-function-to-plot-lm-results-in-r/ source

#}

#ggplotRegression



names(lm_mod1$model)[2]

#total_train$ETH_Volume

coef(lm_mod1)

ggplot(lm_mod1$model, aes_string(x = names(lm_mod1$model)[2], y = names(lm_mod1$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "blue") +
  labs(title = paste("Adj R2 = ",signif(summary(lm_mod1)$adj.r.squared, 5),
                     "Intercept =",signif(lm_mod1$coef[[1]],5 ),
                     "Slope =",signif(lm_mod1$coef[[2]], 5),
                     "P-Val =",signif(summary(lm_mod1)$coef[2,4], 5))) + xlim(0, 2500) + ylim(0, 3000)



ggplot(lm_mod1,aes(x = BTC_Volume, y = ETH_Volume)) +
  stat_summary(fun.data= mean_cl_normal) + 
  geom_smooth(method='lm')

ggplot(lm_mod1,aes(x = ETH_Close, y = BTC_PriceDif)) + 
  geom_point(color='blue') +
  geom_smooth(method = "lm", se = FALSE)

ggplot(lm_mod1,aes(x = BTC_PriceDif, y = ETH_Close)) + 
  geom_point(color='blue') +
  geom_smooth(method = "lm", se = FALSE)

ggplot(lm_mod1,aes(x = BTC_Volume, y = ETH_Close)) + 
  geom_point(color='blue') +
  geom_smooth(method = "lm", se = FALSE)

ggplot(lm_mod1,aes(x = ETH_Volume, y = ETH_Close)) + 
  geom_point(color='blue') +
  geom_smooth(method = "lm", se = FALSE)+ labs(title = "ETH Volume versus ETH Close")


```

```{r}

#total_split <- initial_split(ETH_BTC_USDT, 0.9)
#total_train <- training(total_split)
#total_test <- testing(total_split)

#lm_mod1 = lm(ETH_Volume ~ ETH_Close + BTC_Close + BTC_Volume + #ETH_PriceDif, data = total_train)
summary(lm_mod1)
#lm_mod2 = lm(BTC_Volume ~ BTC_Close + ETH_Close + ETH_Volume + #BTC_PriceDif, data = total_train)
summary(lm_mod2)

preds_train <- predict(lm_mod1, newdata = total_train) ##here is #error
preds_test <- predict(lm_mod1, newdata = total_test)



results_train <- 
  data.frame(
    `preds` = preds_train, #No need to exponentiate
    `true` = total_train$ETH_Close,
    `type` = "train"
  )

results_test <- 
  data.frame(
    `preds` = preds_test, #no exponentiate
    `true` = total_test$ETH_Close,
    `type` = "test"
  )

results_df <- 
  bind_rows(results_train, results_test)

results_df

ggplot(results_df, aes(x = true, y = preds)) + geom_point(aes(color = type)) + geom_abline(mapping = NULL, data = NULL,slope = 1)+ facet_wrap(~ type) + theme_minimal(base_size = 16) + theme(legend.position="bottom")
  
summary(lm_mod1)
  

get_mae <- function(true, predictions){
  mean(abs(true - predictions))
}

get_mae(results_test$true, results_test$preds)
get_mae(results_train$true, results_train$preds)



preds_train <- predict(lm_mod2, newdata = total_train)
preds_test <- predict(lm_mod2, newdata = total_test)

results_train <- 
  data.frame(
    `preds` = preds_train, #No need to exponentiate
    `true` = total_train$BTC_Close,
    `type` = "train"
  )

results_test <- 
  data.frame(
    `preds` = preds_test, #no exponentiate
    `true` = total_test$BTC_Close,
    `type` = "test"
  )

results_df <- 
  bind_rows(results_train, results_test)

results_df

get_mae <- function(true, predictions){
  mean(abs(true - predictions))
}

get_mae(results_test$true, results_test$preds)
get_mae(results_train$true, results_train$preds)

ggplot(results_df, aes(x = true, y = preds)) + geom_point(aes(color = type)) + geom_abline(mapping = NULL, data = NULL,slope = 1)+ facet_wrap(~ type) + theme_minimal(base_size = 16) + theme(legend.position="bottom")

summary(lm_mod1)
summary(lm_mod2)

```
